# -*- coding: utf-8 -*-
"""All page copy in DE and EN. build.py renders both languages from this."""

COLORS = {'irongrid': '#3fbfa6', 'relais': '#e0a23e', 'tonal': '#4cb5f0', 'securitymonitor': '#6f84ff', 'dbnavigator': '#ec0016', 'kfit': '#ff2fa6'}

UI = {
 'de': dict(
  lang='de', other='en', other_label='EN', other_href='/en/',
  title='Constantino Carneiro-Fernández — UX / Fullstack',
  desc='UX / Fullstack-Entwickler in Regensburg. Interfaces für Leitstände, Editoren und Monitoring, entworfen und in Code gebaut.',
  jump='Jump to', jump_m='Menü', sayhi='Say hi',
  term=[('cmd','whoami'),('out','<b>Constantino Carneiro-Fernández</b> · UX / Fullstack · Regensburg'),
        ('cmd','cat stack.txt'),('out','Figma · HTML/CSS/SVG · JavaScript · Angular · PHP/Symfony · PostgreSQL · Docker'),
        ('cmd','ls projects/'),('out','irongrid-2.0/  relais/  tonal/  security-monitor/  db-navigator-rescue/'),
        ('cmd','./run --all')],
  term_m=[('cmd','whoami'),('out','<b>Constantino Carneiro-Fernández</b> · UX / Fullstack'),('cmd','./run --all')],
  demo_open='Live-Demo starten', demo_close='Demo schließen',
  term_title='zsh — farkas-garage',
  h1='Interfaces, die unter <em>Druck</em> lesbar bleiben.',
  lead='Ich entwerfe Oberflächen für Leitstände, Editoren und Monitoring, und baue sie selbst.',
  facts=[('⅓','der Widgets der Website 4.0 (TA Bildungszentrum)'),('19','Hosts im eigenen Security-Lab'),('6 Wo.','Kundenprojekt Angular + Symfony')],
  cta1='Projekte ansehen', cta2='Lebenslauf', scroll='scroll to run',
  avail='verfügbar', loc='Regensburg · Remote',
  work_k='Projekte · 06', work_h='Vier Werkzeuge für den Desktop, zwei Apps fürs Telefon.', work_s='entworfen &amp; in Code gebaut',
  open_case='Case Study öffnen', demo_k='Live-Demo',
  method_k='So arbeite ich', method_h='Verstehen. In Code prototypen. Prüfen.',
  quote='„Ein klickbarer Entwurf ist <em>ehrlicher als ein Bild</em>: Er zeigt, was das System kann und wo es scheitert.“',
  method=[('01','Verstehen, bevor ich zeichne','Welche Daten gibt es wirklich, wer schaut darauf, in welcher Situation?','Beispiel','19 reale Hosts, echte IP-Zonen, ein echter Angriffs-Testfall.'),
          ('02','In Code prototypen','Statt statischer Mockups baue ich Oberflächen in HTML, CSS und SVG, mit echten Zuständen.','Beispiel','TONAL: Waveform und CMYK-Auszüge aus den echten Pixeln.'),
          ('03','Prüfen und aufschreiben','Jede Case Study endet mit Entscheidungen, einer Iteration und dem, was noch fehlt.','Beispiel','RELAIS: „RUN/STOP/MRES“ lief aus dem Modul, gelöst durch Weglassen.')],
  about_k='Lebenslauf', about_h='Ein Beruf, zwei Hälften: Entwurf und Umsetzung.', cv_btn='Lebenslauf öffnen', cv_close='Lebenslauf schließen', cv_nav='CV',
  about_p1='Erst Kommunikationsdesign (Diplom, Düsseldorf, Note 1,4) und Agenturjahre in Interface- und Webdesign, dann Webentwicklung. Heute <b>entwerfe und baue</b> ich Oberflächen selbst, zuletzt Fullstack bei der TA Bildungszentrum GmbH (<b>PHP, Symfony, Twig</b>).',
  about_p2='Zuletzt Fullstack-Entwickler bei der TA Bildungszentrum GmbH (<b>PHP, Symfony, Twig</b>). Ein eigenes OT/IT-Labor liefert die Fachtiefe für IronGrid, RELAIS und den Security Monitor.',
  about_p3='Abseits vom Bildschirm: ein Ultraschall-Radar auf Arduino mit Gate-Treibern und MOSFET-Halbbrücken, Rust auf Codeforces, und Schnee, so viel wie möglich.',
  tools=['Figma','Adobe XD','HTML/CSS/SVG','JavaScript','Angular','PHP · Symfony','Twig','PostgreSQL','Docker','Git','Ansible / DebOps','Grafana','Java'],
  langs=['Deutsch C1','Englisch','Spanisch'],
  timeline=[('2026','Maheri Consulting (USA)','Freelance Fullstack: Security Monitoring Dashboard · Angular, Symfony, PostgreSQL'),
            ('2025 – 2026','TA Bildungszentrum GmbH','Junior Fullstack: PHP 8.4, Symfony, Twig · Website 4.0'),
            ('2022 – 2025','Höhere Berufsausbildung Webentwicklung','DAW · EQF Level 5 · Klassensprecher'),
            ('2016 – 2018','Hesse Design GmbH','Designer, Düsseldorf / Shanghai: Web, Interfaces'),
            ('2011 – 2015','Diplom Kommunikationsdesign','IN.D Düsseldorf · Note 1,4')],
  contact_k='Say hi', contact_h='Offen für Frontend-, Fullstack- und UX-Rollen.', copy='copy', copied='E-Mail kopiert',
  footer_loc='Regensburg · Deutschland',
  ov_close='Schließen', pal_ph='Jump to…  (Esc schließt)', pal_none='nichts gefunden', pal_sec='Abschnitt', pal_case='Case Study', pal_ext='extern',
  pal=[('Projekte','#work'),('So arbeite ich','#method'),('Lebenslauf','#about'),('Kontakt','#contact')],
  # demos
  demo_db_title='Was wäre bei … Minuten Verspätung?', demo_db_hint='Regler bewegen', demo_db_delay='Verspätung ICE 847',
  demo_db_rows=['Anschluss Frankfurt','Ankunft Hamburg','Fahrgastrechte','Modus'],
  demo_iron_title='Alert-Feed · simuliert', demo_iron_hint='Ereignisse laufen ein, PENTEST wird getrennt markiert',
  demo_iron_cols=['Zeit','Quelle','Ereignis','Schwere'],
  demo_relais_title='Selbsthaltung: Start, Stopp, Not-Aus', demo_relais_hint='Taster drücken, Kontaktplan und AWL reagieren',
  demo_relais_btn=['Start E0.0','Stopp E0.1','Not-Aus E0.2'], demo_relais_out='Motor A4.0', demo_relais_awl='AWL · Netzwerk 1', demo_relais_scope='Oszilloskop · A4.0',
  demo_tonal_title='Scopes aus echten Pixeln', demo_tonal_hint='Regler bewegen, Vektorskop und Parade rechnen live',
  demo_tonal_sl=['Temperatur','Sättigung','Kontrast'], demo_tonal_lbl=['Vektorskop','RGB-Parade'],
  demo_try={'iron':'Probier: Warte auf einen PENTEST-Eintrag. Er wird getrennt gezählt, nicht als Alarm.','db':'Probier: Zieh den Regler auf 15 Minuten und schau, was mit dem Anschluss in Frankfurt passiert.','relais':'Probier: Start drücken, dann Not-Aus. Die Selbsthaltung fällt, im AWL kippt das VKE.','tonal':'Probier: Sättigung auf 0 und beobachte, wie das Vektorskop in die Mitte kollabiert.','kfit':'Probier: Intensität auf RPE 10. Die Kurve springt in Z5 und die Kalorien folgen mit Verzögerung.'},
  demo_kfit_title='Session-Rechner: Puls, Zonen, Kalorien', demo_kfit_hint='Regler bewegen, die Kurve rechnet sofort',
  demo_kfit_lbl=['Alter','Gewicht','Geschlecht','Dauer','Intensität','Start','Pause','Nochmal','Kalorien','Ø Puls','Max. Puls','Zeit in Z4–Z5','Arbeit','Erholung','Aufwärmen','weiblich','männlich','Rekord','Fertig','Ausklang','Puls','kcal kumuliert'],
  demo_kfit_prof='Simulation: der Puls folgt der Belastung mit Verzögerung (Aufwärmen, Intervalle 3/1,5 min, Ausklang). HFmax nach Tanaka (208 − 0,7 × Alter), Zielpuls nach Karvonen, Kalorien nach Keytel et al. 2005.',
 ),
 'en': dict(
  lang='en', other='de', other_label='DE', other_href='/',
  title='Constantino Carneiro-Fernández — UX / Fullstack',
  desc='UX / fullstack developer in Regensburg, Germany. Interfaces for control rooms, editors and monitoring, designed and built in code.',
  jump='Jump to', jump_m='Menu', sayhi='Say hi',
  term=[('cmd','whoami'),('out','<b>Constantino Carneiro-Fernández</b> · UX / Fullstack · Regensburg, DE'),
        ('cmd','cat stack.txt'),('out','Figma · HTML/CSS/SVG · JavaScript · Angular · PHP/Symfony · PostgreSQL · Docker'),
        ('cmd','ls projects/'),('out','irongrid-2.0/  relais/  tonal/  security-monitor/  db-navigator-rescue/'),
        ('cmd','./run --all')],
  term_m=[('cmd','whoami'),('out','<b>Constantino Carneiro-Fernández</b> · UX / Fullstack'),('cmd','./run --all')],
  demo_open='Start live demo', demo_close='Close demo',
  term_title='zsh — farkas-garage',
  h1='Interfaces that stay readable under <em>pressure</em>.',
  lead='I design interfaces for control rooms, editors and monitoring, and I build them myself.',
  facts=[('⅓','of the widgets on Website 4.0 (TA Bildungszentrum)'),('19','hosts in my own security lab'),('6 wks','client project, Angular + Symfony')],
  cta1='View projects', cta2='CV', scroll='scroll to run',
  avail='available', loc='Regensburg · Remote',
  work_k='Projects · 06', work_h='Four desktop tools, two apps for the phone.', work_s='designed &amp; built in code',
  open_case='Open case study', demo_k='Live demo',
  method_k='How I work', method_h='Understand. Prototype in code. Verify.',
  quote='“A clickable prototype is <em>more honest than a picture</em>: it shows what the system can do and where it fails.”',
  method=[('01','Understand before I draw','What data really exists, who looks at it, in which situation?','Example','19 real hosts, real IP zones, one real attack test case.'),
          ('02','Prototype in code','Instead of static mockups I build interfaces in HTML, CSS and SVG, with real states.','Example','TONAL: waveform and CMYK separations computed from the actual pixels.'),
          ('03','Verify and write it down','Every case study ends with decisions, one iteration and what is still missing.','Example','RELAIS: the “RUN/STOP/MRES” label overflowed the module; fixed by removing, not shrinking.')],
  about_k='CV', about_h='One profession, two halves: design and implementation.', cv_btn='Open CV', cv_close='Close CV', cv_nav='CV',
  about_p1='First communication design (diploma, Düsseldorf, grade 1.4) and agency years in interface and web design, then web development. Today I <b>design and build</b> interfaces myself, most recently fullstack at TA Bildungszentrum GmbH (<b>PHP, Symfony, Twig</b>).',
  about_p2='Most recently fullstack developer at TA Bildungszentrum GmbH (<b>PHP, Symfony, Twig</b>). My own OT/IT lab provides the domain depth behind IronGrid, RELAIS and the Security Monitor.',
  about_p3='Away from the screen: an ultrasonic radar on Arduino with gate drivers and MOSFET half-bridges, Rust on Codeforces, and as much snow as possible.',
  tools=['Figma','Adobe XD','HTML/CSS/SVG','JavaScript','Angular','PHP · Symfony','Twig','PostgreSQL','Docker','Git','Ansible / DebOps','Grafana','Java'],
  langs=['German C1','English','Spanish'],
  timeline=[('2026','Maheri Consulting (USA)','Freelance fullstack: security monitoring dashboard · Angular, Symfony, PostgreSQL'),
            ('2025 – 2026','TA Bildungszentrum GmbH','Junior fullstack: PHP 8.4, Symfony, Twig · Website 4.0'),
            ('2022 – 2025','Higher vocational training, web development','DAW · EQF level 5 · class representative'),
            ('2016 – 2018','Hesse Design GmbH','Designer, Düsseldorf / Shanghai: web, interfaces'),
            ('2011 – 2015','Diploma in communication design','IN.D Düsseldorf · grade 1.4')],
  contact_k='Say hi', contact_h='Open for frontend, fullstack and UX roles.', copy='copy', copied='Email copied',
  footer_loc='Regensburg · Germany',
  ov_close='Close', pal_ph='Jump to…  (Esc closes)', pal_none='nothing found', pal_sec='section', pal_case='case study', pal_ext='external',
  pal=[('Projects','#work'),('How I work','#method'),('CV','#about'),('Contact','#contact')],
  demo_db_title='What if the train is … minutes late?', demo_db_hint='move the slider', demo_db_delay='Delay ICE 847',
  demo_db_rows=['Connection Frankfurt','Arrival Hamburg','Passenger rights','Mode'],
  demo_iron_title='Alert feed · simulated', demo_iron_hint='events arrive live, PENTEST is tagged separately',
  demo_iron_cols=['Time','Source','Event','Severity'],
  demo_relais_title='Latching circuit: start, stop, e-stop', demo_relais_hint='press the buttons, ladder and STL react',
  demo_relais_btn=['Start I0.0','Stop I0.1','E-Stop I0.2'], demo_relais_out='Motor Q4.0', demo_relais_awl='STL · network 1', demo_relais_scope='Oscilloscope · Q4.0',
  demo_tonal_title='Scopes from real pixels', demo_tonal_hint='move the sliders, vectorscope and parade compute live',
  demo_tonal_sl=['Temperature','Saturation','Contrast'], demo_tonal_lbl=['Vectorscope','RGB parade'],
  demo_try={'iron':'Try: wait for a PENTEST entry. It is counted separately, not raised as an alarm.','db':'Try: drag the slider to 15 minutes and watch what happens to the Frankfurt connection.','relais':'Try: press Start, then E-Stop. The latch drops and the RLO flips in the STL view.','tonal':'Try: saturation to 0 and watch the vectorscope collapse to the centre.','kfit':'Try: intensity to RPE 10. The curve jumps into Z5 and the calories follow with a lag.'},
  demo_kfit_title='Session calculator: heart rate, zones, calories', demo_kfit_hint='move the sliders, the curve recomputes instantly',
  demo_kfit_lbl=['Age','Weight','Sex','Duration','Intensity','Start','Pause','Again','Calories','Avg HR','Max HR','Time in Z4–Z5','Work','Rest','Warm-up','female','male','Record','Done','Cool-down','Heart rate','kcal cumulative'],
  demo_kfit_prof='Simulation: heart rate follows the load with a lag (warm-up, 3/1.5 min intervals, cool-down). HRmax after Tanaka (208 − 0.7 × age), target HR after Karvonen, calories after Keytel et al. 2005.',
 )
}

# per-project content. keys: k (kicker), t (title html), tl (tagline), ds (description), facts [(label,value)], stack [], sys (HUD label), img, alt, gallery [(file,caption)], stats [(n,label)], dec [(h,p)], ovd (overlay description)
PROJECTS = {
 'de': [
  dict(id='irongrid', k='Projekt 01 · OT/IT-Security-Monitoring', t='Iron<em>Grid</em> 2.0', tt='IronGrid 2.0',
   tl='Ein Dashboard, das 19 reale Hosts in fünf Zonen in Sekunden lesbar macht.',
   ds='Eigenes Security-Lab für eine simulierte Gaskraftwerk-Anlage: Topologie, Alert-Feed, Endpunkte, mobile Alarmierung. Ein Red-Team-Test aus dem Attack-Lab wird als PENTEST markiert, nicht als Alarm.',
   facts=[('Rolle','UI/UX · Frontend'),('Werkzeuge','Figma · HTML/CSS'),('Umfang','8 Screens · Mobile'),('Jahr','2026')],
   stack=['Suricata','Wazuh','DebOps','Modbus TCP'], sys='SYSTEM ONLINE · 19 HOSTS', img='iron-1.jpg', alt='IronGrid 2.0 Netzwerktopologie', demo='iron',
   ovd='Ein Security-Dashboard für eine simulierte Gaskraftwerk-Anlage, von der Netzwerktopologie bis zur mobilen Alarmierung für Operatoren.',
   gallery=[('iron-1.jpg','Netzwerktopologie: alle fünf Zonen, 19 Hosts. firewall-gw läuft mit nftables, das Attack-Lab sitzt isoliert im eigenen /99-Bereich.'),('iron-2.jpg','Sicherheit: Alert-Feed nach Schwere. Der Red-Team-Test wird als PENTEST markiert, nicht als Alarm.'),('iron-3.jpg','Endpunkte: ehrliches Inventar. vulnerable-host läuft absichtlich auf Debian 9 (EOL), dokumentiert statt versteckt.'),('iron-4.jpg','Mobile: kein verkleinertes Dashboard, sondern Push → Inbox → Aktion in drei Sekunden.'),('iron-5.jpg','Modbus-Traffic: der Anomalie-Peak zeigt den Kontext vor der Entscheidung.')],
   stats=[('19','Geräte im Lab'),('5','Netzwerkzonen'),('8','Dashboard-Screens'),('12 s','Erkennungszeit')],
   dec=[('Warum Dark Mode','Reale Leitstände laufen dunkel: weniger Ermüdung bei Dauerüberwachung, mehr Kontrast für die drei Alarmfarben.'),('Farbe nie allein','Status wird immer über Farbe und Wort kommuniziert, funktioniert auch bei Farbfehlsichtigkeit.'),('Eine Iteration','Vom Split-Layout zum flexiblen Raster: die Netzwerkseite bekam eine Spalte, die sich dem Inhalt anpasst.'),('Vor einem Rollout noch','Kontraste gegen WCAG prüfen, mit Operatoren testen, klickbarer Prototyp.')]),
  dict(id='relais', k='Projekt 02 · Lernsimulator für SPS', t='RE<em>LAIS</em>', tt='RELAIS',
   tl='SPS lernen wie ein Spiel, ohne die Realität zu verbiegen.',
   ds='Kontaktplan-Editor, AWL-Konsole mit Röntgenblick in die CPU, HMI-Prozessbild und Lektionen. Wer RELAIS beherrscht, findet sich in professioneller Steuerungssoftware wieder.',
   facts=[('Rolle','UX/UI · Frontend'),('Werkzeuge','HTML/CSS · SVG'),('Umfang','6 Screens · Lernmodus'),('Jahr','2026')],
   stack=['Kontaktplan','AWL','HMI','SVG'], sys='CPU RUN · ZYKLUS 26 MS', img='relais-1.jpg', alt='RELAIS Editor', demo='relais',
   ovd='Ein spielerischer Simulator, der Kontaktplan, AWL und echte Hardware-Diagnose in kleinen Lektionen vermittelt, mit Konsole, HMI-Prozessbild und sofortigem Feedback.',
   gallery=[('relais-1.jpg','Die echte Werkbank, nur freundlicher: Kontaktplan, AWL, Hardware-Rack und HUD, immer konsistent.'),('relais-2.jpg','Röntgenblick in die CPU: VKE, AKKU1, AKKU2, Statuswort live unter der Konsole.'),('relais-3.jpg','Modul-Diagnose: Kanaltabelle mit Strom und Hinweis, „Kanal forcen“ bewusst nicht die Primäraktion.'),('relais-4.jpg','Lektion abgeschlossen: Sterne und XP belohnen, Zeit und Fehler erklären, warum zwei statt drei.'),('relais-5.jpg','Vorher: der Pixelart-Prototyp. Charmant, aber falsch fürs Ziel. Die zweite Fassung tauscht Stil gegen Substanz.')],
   stats=[('8','Lektionen'),('6','Screens'),('4','Netzwerke (OB1)'),('1','Prozessbild')],
   dec=[('Echte Editor-Oberfläche behalten','Kein Spielzeug-Look. Das Lernziel ist die professionelle Werkbank.'),('Amber = Lernen','Eine Farbe exklusiv für Hinweise, Lektion und Konsole: Didaktik trennt sich sichtbar von Anlage und Alarm.'),('Der überlaufende Schalter','„RUN / STOP / MRES“ kollidierte mit der LED-Spalte. Reduziert auf „MODE“: die Lektion erklärt die Stellungen, nicht das Bauteil.'),('Vor einem Rollout noch','Die Konsole wirklich ausführen (AWL-Parser), mit Azubis testen, Kontraste prüfen.')]),
  dict(id='tonal', k='Projekt 03 · Farb- und Bildbearbeitung · macOS', t='TO<em>NAL</em>', tt='TONAL',
   tl='Grading wie im Schnittraum, für ein einzelnes Bild.',
   ds='Ein Prototyp, der rechnet statt illustriert: Waveform, Vektorskop, CIE-Farbwolke und CMYK-Auszüge entstehen aus den echten Pixeln. Looks als Node-Graph. Die Oberfläche für ein Produkt, das in Swift und Metal entsteht.',
   facts=[('Rolle','UX/UI · Prototyp'),('Werkzeuge','HTML/CSS · Canvas · SVG'),('Umfang','3 Screens · Live-Scopes'),('Status','In Entwicklung')],
   stack=['Canvas','CIE 1931','Node-Graph','Soft-Proof'], sys='METAL · 3 SCOPES LIVE', img='tonal-1.jpg', alt='TONAL Color-Ansicht', demo='tonal',
   ovd='Ein Grading-Werkzeug für Fotografen im Geist professioneller Video-Color-Suites: ruhige Oberfläche, echte Scopes, Node-Graph für Looks und eine Ansicht, die die Farbwissenschaft dahinter sichtbar macht.',
   gallery=[('tonal-1.jpg','Color: die Bühne bleibt grau, damit das Bild die Wahrheit sagt. Farbräder, Kurven, LUT rechts, A|B-Wipe im Viewer.'),('tonal-2.jpg','Science: CIE-Diagramm mit Gamuts, echte Farbwolke des Bildes, CMYK-Auszüge, Soft-Proof FOGRA39.'),('tonal-3.jpg','Nodes: ein Look ist ein Graph, keine Reihenfolge. 9 Knoten, 11 Verbindungen, Metal-Kernel pro Node.'),('tonal-4.jpg','Scopes aus dem Bild: Parade, Vektorskop und Log-Histogramm zeigen den Blaustich der Nacht.'),('tonal-5.jpg','CMYK-Auszüge: Cyan, Magenta, Gelb, Schwarz live getrennt, mit Flächendeckung pro Platte.')],
   stats=[('3','Scopes · live'),('6','Farbräume'),('9','Node-Typen'),('4','Farbmodelle')],
   dec=[('Neutrales Chrom','Kein gesättigtes UI in einem Farbwerkzeug. Zwei Akzente mit klarer Bedeutung: aktiv und Maske.'),('Scopes rechnen, nicht illustrieren','Waveform, Vektorskop, CIE-Wolke und CMYK aus echten Pixeln, prüfbar mit jedem Bild.'),('Das Histogramm, das alles weiß färbte','Nicht andere Farbe, sondern weniger davon: Deckkraft ein Drittel, Höhe 82 %, Log-Skala behalten.'),('Vor einem Rollout noch','Mit Coloristen testen, Farbmanagement absichern (OCIO, ICC), Tastatur-Präzision definieren.')]),
  dict(id='securitymonitor', k='Projekt 04 · Kundenprojekt · White-Label', t='Security <em>Monitor</em>', tt='Security Monitor',
   tl='Ein Code, jede Marke: Theme-Tokens zur Laufzeit.',
   ds='Multi-Mandanten-Dashboard für Maheri Consulting (USA): Alerts, Detailansicht, Maßnahmen, Theme pro Kunde. Sechs Wochen, Angular und Symfony. Gezeigt wird ein Nachbau mit simulierten Daten; der Kundencode bleibt vertraulich.',
   facts=[('Rolle','Fullstack · UI/UX'),('Stack','Angular · Symfony · PostgreSQL'),('Umfang','4 Ansichten · 3 Mandanten'),('Zeitraum','Jun–Jul 2026')],
   stack=['Angular','Symfony','PostgreSQL','Theme-Tokens'], sys='LIVE · 3 MANDANTEN', img='sm-1.jpg', alt='Security Monitor Übersicht', demo=None,
   ovd='Ein Web-Dashboard für Security- und Netzwerk-Events, entwickelt für Maheri Consulting Services Network (USA): eigenes Werkzeug der Beratung und White-Label-Komponente für deren Kunden. Sechs Wochen, Angular und Symfony.',
   gallery=[('sm-1.jpg','Übersicht: vier Zahlen, ein Verlauf, und sofort die Frage: Was ist neu? Jede Kennzahl trägt eine Sparkline.'),('sm-2.jpg','Alert-Liste: Filter als Chips, Suchsyntax host:… OR sip:…, Sammelaktionen erscheinen erst, wenn Zeilen markiert sind.'),('sm-3.jpg','Detailansicht: Zeitverlauf mit Korrelation, Roh-Ereignis aus Wazuh mit Syntaxfarben, MITRE T1110, SLA-Timer.'),('sm-4.jpg','White-Label: Theme-Tokens zur Laufzeit. Dieselbe Übersicht in vier Marken, Schweregrade bleiben unverändert.')],
   stats=[('6','Wochen'),('4','Ansichten'),('3','Mandanten'),('2','Datenquellen')],
   dec=[('Material-Konventionen statt eigener Bibliothek','Sechs Wochen erlauben keine Komponentenbibliothek. Gestaltung liegt in Dichte und Hierarchie.'),('Schwere bleibt markenunabhängig','Die Primärfarbe wechselt pro Mandant, die vier Alarmfarben nie.'),('Die Sammelaktion, die im Weg stand','48 Pixel dauerhaft über der Tabelle, für nichts. Jetzt nur noch, wenn Zeilen ausgewählt sind.'),('Den Nachbau kennzeichnen','Gezeigt wird die Oberfläche mit simulierten Daten; der Kundencode bleibt vertraulich.')]),
  dict(id='dbnavigator', k='Projekt 05 · Mobile · Konzeptstudie', t='DB Navigator <em>Rescue</em>', tt='DB Navigator · Rescue',
   tl='Wenn die Reise bricht, repariert die App sie.',
   ds='Ein Konzept für die nächste Generation der Bahn-App: Reise beobachten, Folgen erklären, Alternativen finden, Fahrgastrechte vorbereiten. 21 Screens, fünf Zustände. Nicht im Auftrag der Deutschen Bahn.',
   facts=[('Rolle','UX/UI · Konzept'),('Plattform','iOS · 390×844'),('Umfang','21 Screens · 5 Zustände'),('Status','Konzeptstudie 2026')],
   stack=['Figma','iOS','Rescue-Modus','Wallet'], sys='ICE 847 · +6 MIN · IM BLICK', img=('db-2.jpg','db-4.jpg'), alt=('Alles in Ordnung','Rescue-Modus'), demo='db',
   ovd='Wenn die Reise bricht, hilft die App, sie zu reparieren, statt dem Fahrgast das Bahnproblem zu überlassen. 21 Screens im Erscheinungsbild des heutigen DB Navigator. Nicht im Auftrag der Deutschen Bahn.',
   gallery=[('db-2.jpg','Zustand 1: ein Blick, ein Satz, ein Rot. Die App verspricht, sich nur zu melden, wenn sich etwas ändert.'),('db-3.jpg','Gefährdet: 72 % Risiko, 3 Minuten Umstieg. „Wir berechnen Alternativen“, Klartext statt Prozentzahl.'),('db-4.jpg','Rescue: ICE 72 ausgefallen, drei Alternativen berechnet, Fahrgastrechte werden im Hintergrund vorbereitet.'),('db-5.jpg','Was-wäre-wenn-Regler: ein Regler, fünf Konsequenzen: Anschluss, Ankunft, Zug, Rechte, Modus.'),('db-6.jpg','Wagenreihung und Sitzplan: eigener Wagen rot, Sitz 42 markiert.'),('db-7.jpg','Live-Karte: echter Zug groß und rot, Richtung und Gleis im Chip.')],
   stats=[('21','Screens'),('5','Reisezustände'),('1','roter Button'),('0','juristische Sätze')],
   dec=[('Kognitive Last ist das Problem','Nicht fehlende Daten. Die App interpretiert die Folgen, warnt früh, findet Alternativen.'),('Rot ist DB und trotzdem sparsam','Einmal pro Screen, für die eine Aktion, die zählt.'),('Nie ein falsches Versprechen','„wahrscheinlich“ statt „garantiert“, ein Foto statt eines Formulars.'),('Der einzige dunkle Moment','Fällt der Zug aus, kippt der Screen ins Grafit: etwas Ernstes ist passiert, und die App übernimmt.')]),
  dict(id='kfit', k='Projekt 06 · Produktkonzept & App-Design', t='KF<em>IT</em>', tt='KFIT',
   tl='Vom Instagram-Video zur Routine, die man verfolgen, protokollieren und verbessern kann.',
   ds='Trainings-App für die Schützlinge einer HYROX-Trainerin: Übungsbibliothek, Session-Modus, Fortschritt und eine Coach-Ansicht zum Planen per Drag-and-drop. Installierbare Web-App für eine Person ohne Budget. Konzeptstudie, kein bezahlter Auftrag.',
   facts=[('Rolle','UX/UI · Produktkonzept'),('Plattform','PWA · iOS & Android'),('Umfang','13 Screens · 2 Rollen'),('Status','Konzeptstudie 2026')],
   stack=['Figma','PWA','YouTube','PostgreSQL'], sys='HYROX · WOCHE 3 VON 8', img='kfit-1.jpg', alt='KFIT Übungsbibliothek und Session-Modus', demo='kfit',
   ovd='Eine HYROX-Trainerin bringt ihre Routinen sonst über Instagram-Storys und WhatsApp unter die Leute — die Schützlinge folgen halb, protokollieren nichts, und sie sieht nicht, wer trainiert hat. KFIT macht daraus eine App: Video hochladen, Routine per Drag-and-drop bauen, sehen, wer zurückfällt. Mehr nicht.',
   gallery=[('kfit-1.jpg','Alumno-Flow: von der Bibliothek in die Session, ohne den Daumen zu bewegen. Videos nach Station gefiltert, jedes unter einer Minute.'),('kfit-2.jpg','Fortschritt: acht Wochen als Kurve, der Rekord in Gelb, der Puls aus Strava, das Gewicht. Gespeichert wird nur, was zählt.'),('kfit-3.jpg','Coach-Ansicht: drei Zahlen sagen der Trainerin, wer diese Woche einen Anstoß braucht. Neue Übung per Video, Routine per Drag-and-drop.'),('kfit-4.jpg','Startscreen, Premium und Buchung: ihre Stimme statt WhatsApp, ein Schloss statt einer Mauer.'),('kfit-5.jpg','Drei kleine Entscheidungen, die man im Gym merkt: der Timer aus zwei Metern lesbar, das Panel mit einem einzigen gelben Wert, das Ablegen mit sprechenden Lücken.')],
   stats=[('13','Screens'),('2','Rollen'),('8','Wochen-Plan'),('0 €','Budget')],
   dec=[('Web-App, kein Store','Installierbare PWA für iOS und Android, keine Store-Provision, Update direkt aus dem Browser.'),('Nur Dark Mode','Die Palette stammt aus ihrem Instagram: dunkle Gyms, Neon, pinke Schuhe. Gelb erscheint nur bei einem Rekord oder einer Warnung.'),('Gesundheitsdaten getrennt','Puls, Gewicht und Schlaf sind sensibel: eigene Einwilligung, eigene Tabelle, ein Knopf, der alles löscht.'),('Vor einem Launch noch','Mit fünf echten Schützlingen testen, Strava anbinden, die Bezahlung für Mexiko einrichten.')]),
 ],
 'en': [
  dict(id='irongrid', k='Project 01 · OT/IT security monitoring', t='Iron<em>Grid</em> 2.0', tt='IronGrid 2.0',
   tl='A dashboard that makes 19 real hosts in five zones readable in seconds.',
   ds='My own security lab for a simulated gas power plant: topology, alert feed, endpoints, mobile alerting. A red-team test from the attack lab is tagged PENTEST, not raised as an alarm.',
   facts=[('Role','UI/UX · Frontend'),('Tools','Figma · HTML/CSS'),('Scope','8 screens · mobile'),('Year','2026')],
   stack=['Suricata','Wazuh','DebOps','Modbus TCP'], sys='SYSTEM ONLINE · 19 HOSTS', img='iron-1.jpg', alt='IronGrid 2.0 network topology', demo='iron',
   ovd='A security dashboard for a simulated gas power plant, from the network topology to mobile alerting for operators.',
   gallery=[('iron-1.jpg','Network topology: all five zones, 19 hosts. firewall-gw runs nftables; the attack lab sits isolated in its own /99 range.'),('iron-2.jpg','Security: alert feed by severity. The red-team test is tagged PENTEST, not raised as an alarm.'),('iron-3.jpg','Endpoints: an honest inventory. vulnerable-host deliberately runs Debian 9 (EOL), documented rather than hidden.'),('iron-4.jpg','Mobile: not a shrunken dashboard but push → inbox → action in three seconds.'),('iron-5.jpg','Modbus traffic: the anomaly peak gives context before the decision.')],
   stats=[('19','devices in the lab'),('5','network zones'),('8','dashboard screens'),('12 s','detection time')],
   dec=[('Why dark mode','Real control rooms run dark: less fatigue during continuous monitoring, more contrast for the three alarm colours.'),('Never colour alone','Status is always communicated by colour and word; it works with colour-vision deficiency too.'),('One iteration','From split layout to a flexible grid: the network page got a column that adapts to its content.'),('Before a rollout','Check contrast against WCAG, test with operators, build a clickable prototype.')]),
  dict(id='relais', k='Project 02 · PLC learning simulator', t='RE<em>LAIS</em>', tt='RELAIS',
   tl='Learn PLC programming like a game, without bending reality.',
   ds='Ladder editor, STL console with an X-ray view into the CPU, HMI process picture and lessons. Whoever masters RELAIS will recognise professional engineering software.',
   facts=[('Role','UX/UI · Frontend'),('Tools','HTML/CSS · SVG'),('Scope','6 screens · learning mode'),('Year','2026')],
   stack=['Ladder (LAD)','STL','HMI','SVG'], sys='CPU RUN · CYCLE 26 MS', img='relais-1.jpg', alt='RELAIS editor', demo='relais',
   ovd='A playful simulator that teaches ladder logic, STL and real hardware diagnostics in small lessons, with a console, an HMI process picture and instant feedback.',
   gallery=[('relais-1.jpg','The real workbench, only friendlier: ladder, STL, hardware rack and HUD, always consistent.'),('relais-2.jpg','X-ray view into the CPU: RLO, ACCU1, ACCU2 and status word live under the console.'),('relais-3.jpg','Module diagnostics: channel table with current and hint; “force channel” is deliberately not the primary action.'),('relais-4.jpg','Lesson complete: stars and XP reward, time and errors explain why two instead of three.'),('relais-5.jpg','Before: the pixel-art prototype. Charming, but wrong for the goal. The second version trades style for substance.')],
   stats=[('8','lessons'),('6','screens'),('4','networks (OB1)'),('1','process picture')],
   dec=[('Keep the real editor UI','No toy look. The learning goal is the professional workbench.'),('Amber = learning','One colour exclusively for hints, lesson and console: teaching is visibly separate from plant and alarm.'),('The overflowing switch','“RUN / STOP / MRES” collided with the LED column. Reduced to “MODE”: the lesson explains the positions, not the part.'),('Before a rollout','Actually execute the console (STL parser), test with apprentices, check contrast.')]),
  dict(id='tonal', k='Project 03 · Colour and image grading · macOS', t='TO<em>NAL</em>', tt='TONAL',
   tl='Grading like in the edit suite, for a single image.',
   ds='A prototype that computes instead of illustrating: waveform, vectorscope, CIE colour cloud and CMYK separations come from the actual pixels. Looks as a node graph. The interface for a product being built in Swift and Metal.',
   facts=[('Role','UX/UI · Prototype'),('Tools','HTML/CSS · Canvas · SVG'),('Scope','3 screens · live scopes'),('Status','In development')],
   stack=['Canvas','CIE 1931','Node graph','Soft-proof'], sys='METAL · 3 SCOPES LIVE', img='tonal-1.jpg', alt='TONAL colour view', demo='tonal',
   ovd='A grading tool for photographers in the spirit of professional video colour suites: a calm interface, real scopes, a node graph for looks and a view that makes the colour science behind it visible.',
   gallery=[('tonal-1.jpg','Colour: the stage stays grey so the image tells the truth. Colour wheels, curves, LUT on the right, A|B wipe in the viewer.'),('tonal-2.jpg','Science: CIE diagram with gamuts, the image’s real colour cloud, CMYK separations, soft-proof FOGRA39.'),('tonal-3.jpg','Nodes: a look is a graph, not a sequence. 9 nodes, 11 links, one Metal kernel per node.'),('tonal-4.jpg','Scopes from the image: parade, vectorscope and log histogram show the blue cast of the night.'),('tonal-5.jpg','CMYK separations: cyan, magenta, yellow, black separated live, with ink coverage per plate.')],
   stats=[('3','scopes · live'),('6','colour spaces'),('9','node types'),('4','colour models')],
   dec=[('Neutral chrome','No saturated UI in a colour tool. Two accents with clear meaning: active and mask.'),('Compute scopes, don’t illustrate them','Waveform, vectorscope, CIE cloud and CMYK from real pixels, verifiable with any image.'),('The histogram that turned everything white','Not a different colour, but less of it: one-third opacity, 82 % height, log scale kept.'),('Before a rollout','Test with colourists, secure colour management (OCIO, ICC), define keyboard precision.')]),
  dict(id='securitymonitor', k='Project 04 · Client project · White label', t='Security <em>Monitor</em>', tt='Security Monitor',
   tl='One codebase, every brand: theme tokens at runtime.',
   ds='Multi-tenant dashboard for Maheri Consulting (USA): alerts, detail view, actions, one theme per client. Six weeks, Angular and Symfony. Shown here as a rebuild with simulated data; the client code stays confidential.',
   facts=[('Role','Fullstack · UI/UX'),('Stack','Angular · Symfony · PostgreSQL'),('Scope','4 views · 3 tenants'),('Period','Jun–Jul 2026')],
   stack=['Angular','Symfony','PostgreSQL','Theme tokens'], sys='LIVE · 3 TENANTS', img='sm-1.jpg', alt='Security Monitor overview', demo=None,
   ovd='A web dashboard for security and network events, built for Maheri Consulting Services Network (USA): the consultancy’s own tool and a white-label component for their clients. Six weeks, Angular and Symfony.',
   gallery=[('sm-1.jpg','Overview: four numbers, one trend, and immediately the question: what is new? Every KPI carries a sparkline.'),('sm-2.jpg','Alert list: filters as chips, search syntax host:… OR sip:…, bulk actions appear only when rows are selected.'),('sm-3.jpg','Detail view: timeline with correlation, raw Wazuh event with syntax colours, MITRE T1110, SLA timer.'),('sm-4.jpg','White label: theme tokens at runtime. The same overview in four brands; severities stay unchanged.')],
   stats=[('6','weeks'),('4','views'),('3','tenants'),('2','data sources')],
   dec=[('Material conventions instead of a custom library','Six weeks do not allow a component library. Design lives in density and hierarchy.'),('Severity stays brand-independent','The primary colour changes per tenant; the four alarm colours never do.'),('The bulk action that got in the way','48 pixels permanently above the table, for nothing. Now only when rows are selected.'),('Label the rebuild','What you see is the interface with simulated data; the client code stays confidential.')]),
  dict(id='dbnavigator', k='Project 05 · Mobile · Concept study', t='DB Navigator <em>Rescue</em>', tt='DB Navigator · Rescue',
   tl='When the journey breaks, the app repairs it.',
   ds='A concept for the next generation of the German rail app: watch the journey, explain consequences, find alternatives, prepare passenger rights. 21 screens, five states. Not commissioned by Deutsche Bahn.',
   facts=[('Role','UX/UI · Concept'),('Platform','iOS · 390×844'),('Scope','21 screens · 5 states'),('Status','Concept study 2026')],
   stack=['Figma','iOS','Rescue mode','Wallet'], sys='ICE 847 · +6 MIN · WATCHING', img=('db-2.jpg','db-4.jpg'), alt=('All good','Rescue mode'), demo='db',
   ovd='When the journey breaks, the app helps repair it instead of leaving the railway’s problem to the passenger. 21 screens in the look of today’s DB Navigator. Not commissioned by Deutsche Bahn.',
   gallery=[('db-2.jpg','State 1: one glance, one sentence, one red. The app promises to speak up only when something changes.'),('db-3.jpg','At risk: 72 % risk, 3-minute transfer. “We are computing alternatives”, plain language instead of a percentage.'),('db-4.jpg','Rescue: ICE 72 cancelled, three alternatives computed, passenger rights prepared in the background.'),('db-5.jpg','What-if slider: one slider, five consequences: connection, arrival, train, rights, mode.'),('db-6.jpg','Coach sequence and seat map: own coach in red, seat 42 marked.'),('db-7.jpg','Live map: own train large and red, direction and platform in the chip.')],
   stats=[('21','screens'),('5','journey states'),('1','red button'),('0','legal sentences')],
   dec=[('Cognitive load is the problem','Not missing data. The app interprets consequences, warns early, finds alternatives.'),('Red is DB and still sparse','Once per screen, for the one action that counts.'),('Never a false promise','“likely” instead of “guaranteed”, a photo instead of a form.'),('The only dark moment','If the train is cancelled the screen turns graphite: something serious happened, and the app takes over.')]),
  dict(id='kfit', k='Project 06 · Product concept & app design', t='KF<em>IT</em>', tt='KFIT',
   tl='From an Instagram video to a routine you can follow, log and improve.',
   ds='A training app for the students of a HYROX coach: an exercise library, a session mode, progress, and a coach view for planning by drag-and-drop. An installable web app for one person with no budget. Concept study, not a paid commission.',
   facts=[('Role','UX/UI · Product concept'),('Platform','PWA · iOS & Android'),('Scope','13 screens · 2 roles'),('Status','Concept study 2026')],
   stack=['Figma','PWA','YouTube','PostgreSQL'], sys='HYROX · WEEK 3 OF 8', img='kfit-1.jpg', alt='KFIT exercise library and session mode', demo='kfit',
   ovd='A HYROX coach normally shares her routines through Instagram stories and WhatsApp — students follow along half-heartedly, log nothing, and she cannot see who trained. KFIT turns that into an app: upload a video, build a routine by drag-and-drop, see who is falling behind. Nothing more.',
   gallery=[('kfit-1.jpg','Student flow: from the library into the session without moving your thumb. Videos filtered by station, each under a minute.'),('kfit-2.jpg','Progress: eight weeks as a curve, the record in yellow, heart rate from Strava, weight. Only what matters is stored.'),('kfit-3.jpg','Coach view: three numbers tell the coach who needs a nudge this week. New exercise by video, routine by drag-and-drop.'),('kfit-4.jpg','Home screen, Premium and booking: her voice instead of WhatsApp, a lock rather than a wall.'),('kfit-5.jpg','Three small decisions you feel in the gym: a timer readable from two metres, a panel with a single yellow value, drag-and-drop with slots that speak.')],
   stats=[('13','Screens'),('2','Roles'),('8','Week plan'),('0 €','Budget')],
   dec=[('Web app, no store','Installable PWA for iOS and Android, no store commission, updates straight from the browser.'),('Dark mode only','The palette comes from her Instagram: dark gyms, neon, pink shoes. Yellow appears only for a record or a warning.'),('Health data kept apart','Heart rate, weight and sleep are sensitive: separate consent, a separate table, one button that deletes it all.'),('Before any launch','Test with five real students, connect Strava, set up payment for Mexico.')]),
 ]
}

# DB demo consequence text per language; function of delay minutes
DB_DEMO = {
 'de': dict(states=[('SICHER','Alles in Ordnung.'),('IM BLICK','Anschluss hält, wir beobachten.'),('GEFÄHRDET','Umstieg knapp, Alternativen werden berechnet.'),('VERPASST','Anschluss verpasst, Ersatz reserviert.'),('RESCUE','Rescue-Modus: wir bringen dich nach Hause.')],
   conn=['Frankfurt 10:51 · Gleis 9 · sicher','Frankfurt 10:51 · Umstieg {u} min','Frankfurt · Umstieg {u} min · 72 % Risiko','Frankfurt · verpasst · ICE 578 11:13','Frankfurt · verpasst · 3 Alternativen'],
   arr=['Hamburg 13:41 · planmäßig','Hamburg 13:41 · unverändert','Hamburg vsl. 14:07 · +26 min','Hamburg 14:07 · +26 min','Hamburg 14:07 · Sitzplatz frei'],
   rights=['keine','keine','vorbereitet, falls nötig','ab +60 min: 25 % Entschädigung','Entschädigung + Taxi möglich'],
   unit='min'),
 'en': dict(states=[('SAFE','All good.'),('WATCHING','Connection holds, we are watching.'),('AT RISK','Transfer tight, computing alternatives.'),('MISSED','Connection missed, replacement reserved.'),('RESCUE','Rescue mode: we will get you home.')],
   conn=['Frankfurt 10:51 · platform 9 · safe','Frankfurt 10:51 · transfer {u} min','Frankfurt · transfer {u} min · 72 % risk','Frankfurt · missed · ICE 578 11:13','Frankfurt · missed · 3 alternatives'],
   arr=['Hamburg 13:41 · on time','Hamburg 13:41 · unchanged','Hamburg est. 14:07 · +26 min','Hamburg 14:07 · +26 min','Hamburg 14:07 · seat available'],
   rights=['none','none','prepared if needed','from +60 min: 25 % compensation','compensation + taxi possible'],
   unit='min'),
}

IRON_DEMO = {
 'de': [('suricata','ET SCAN Nmap SYN-Scan erkannt','warning'),('wazuh','Mehrfache fehlgeschlagene SSH-Logins · web-prod-03','critical'),('plc-sim','Modbus-Traffic: Anomalie-Peak','warning'),('suricata','TLS-Zertifikat läuft in 7 Tagen ab','info'),('kali-attacker','Szenario erkannt: kali-attacker → vulnerable-host','pentest'),('wazuh','Agent 14 offline seit 4 min','warning'),('ids-srv','Signaturen aktualisiert (ET Open)','info'),('wazuh','Neuer Benutzer angelegt · dc-01','critical'),('plc-sim','Coil 40012 gesetzt · außerhalb Schicht','warning'),('firewall-gw','nftables: 312 Pakete verworfen','info')],
 'en': [('suricata','ET SCAN Nmap SYN scan detected','warning'),('wazuh','Multiple failed SSH logins · web-prod-03','critical'),('plc-sim','Modbus traffic: anomaly peak','warning'),('suricata','TLS certificate expires in 7 days','info'),('kali-attacker','Scenario detected: kali-attacker → vulnerable-host','pentest'),('wazuh','Agent 14 offline for 4 min','warning'),('ids-srv','Signatures updated (ET Open)','info'),('wazuh','New user created · dc-01','critical'),('plc-sim','Coil 40012 set · outside shift','warning'),('firewall-gw','nftables: 312 packets dropped','info')],
}

# Digital CV shown in an overlay. Same content as the PDF CVs, without the phone number.
CV = {
 'de': dict(
  name='Constantino Carneiro-Fernández',
  head='Fullstack Webentwickler · Problem Solver · Cybersecurity Enthusiast',
  meta=[('Ort','Regensburg, Deutschland',''),('E-Mail','ccf.szilard@gmail.com','mailto:ccf.szilard@gmail.com'),('LinkedIn','constantino-c-2957731a2','https://www.linkedin.com/in/constantino-c-2957731a2'),('GitHub','Farkas404','https://github.com/Farkas404')],
  profile='Seit 2015 baue ich Software und Websites. Entwicklung ist mein Kerngeschäft: PHP, Symfony, WordPress und TYPO3 gehören zum Alltag. Mein Diplom in Kommunikationsdesign (Note 1,4) und die Höhere Berufsausbildung in Webentwicklung (DAW, Spanien) geben mir zusätzlich ein geschultes Auge für Nutzerführung. Im Kern bin ich Problem Solver: Ich zerlege Dinge gerne, um zu verstehen, wie sie wirklich funktionieren (aktiv auf HackTheBox). Stärkste Programmiersprache: Java.',
  skills_k='Kompetenzen',
  skills=[('Programmiersprachen','Java, JavaScript, TypeScript, C++, Rust'),('CMS & Fullstack','PHP, Symfony, WordPress, TYPO3'),('Frontend','Angular, TypeScript, Bootstrap 5.3'),('UX & Problemlösung','Schnittstelle Design/Dev, Nutzerführung, iteratives Prototyping'),('Automatisierung & KI','n8n, Ollama, Python/Streamlit'),('Sprachen','Deutsch (C1) · Englisch & Spanisch (Muttersprache)')],
  sections=[
   ('Berufserfahrung',[
     ('Jun – Jul 2026','Freelance Fullstack Entwickler','Maheri Consulting Services Network · Security Monitoring Dashboard · Projektbasis (6 Wochen)',['Web-Dashboard zur Visualisierung von Security-Events (Alerts, Logs, Systemstatus), als Tool und White-Label-Komponente.','Frontend: Angular (TypeScript), responsives Layout. Backend: PHP/Symfony, PostgreSQL-Datenmodell.','Vorbereitung der Integration von Wazuh/Suricata als Datenquelle.','Git-Workflow (Sourcetree) mit Feature-Branches und Deployment-Doku.']),
     ('Nov 2025 – Jun 2026','Junior Fullstack Entwickler','TA Bildungszentrum · Website 4.0 Projekt',['Über 30 von insgesamt 80+ CMS-Widgets der Website (rund ein Drittel) eigenständig entwickelt: PHP 8.4, Symfony, Doctrine, Twig, SCSS, JavaScript.','Responsive Layouts mit Bootstrap 5.3; Bereinigung älterer Tailwind-Komponenten.','News-Modul mit CRUD, Kategorien, Filtern und Pagination.','CKEditor-Workflows erweitert: Medienverwaltung, Bildauswahl, Page-Picker, interne Verlinkung.','Git, Feature-Branches, Code-Review; biweekly Sprints mit YouTrack.']),
   ]),
   ('Ausgewählte Projekte',[
     ('','iOS Foto-Editing-App','Co-entwickelt in Swift und C++',['Native iOS-App zur Fotobearbeitung, GPU-beschleunigtes Rendering über Metal.','Rechenintensive Bildverarbeitung in C++, angebunden an Swift-UI; geplante Open-Source-Veröffentlichung.']),
     ('','IronGrid 2.0 – OT/IT Security Lab','Privates Projekt',['Isoliertes Netzwerk (Linux-VMs, Firewall, DNS, Apache), SCADA/HMI mit OpenPLC/Modbus TCP.','Suricata (IDS), Wazuh (SIEM), Monitoring mit PostgreSQL/Grafana, automatisiert über Ansible.']),
   ]),
   ('Weitere Berufserfahrung',[
     ('Apr 2018','Co-Referent – Data-Mining-Seminar, Allianz SE','freiberuflich',['Co-Referent bei zweitägigem Data-Mining-Workshop, Allianz-SE-Zentrale München.']),
     ('Mai 2016 – Apr 2018','Designer','Hesse Design GmbH, Düsseldorf / Shanghai',['Website & Interface für „bola“: UX-Konzeption, Widget-Entwicklung, Tablet/Mobile-Anpassung, Mailchimp-Integration.','UI/UX-Design, Klick-Dummies und Prototypen für mehrere interne Agentur-Seiten.','Wireframes & Website-Konzept für Juwelier Pletzsch (Ring-Konfigurator).']),
     ('2015 – 2019','Freiberuflicher Entwickler','Düsseldorf',['Web-Widgets für die „SMS Website“ (SMS Group, über LK Aktiengesellschaft), u. a. Heavy Plate Mill, Hot Metal Treatment, SAF Ferro Alloys, SAF Silicon, Drive Technology.','Willy Heckmann (mehrere Monate): Produktdatenpflege für hunderte/tausende Produkte; responsive Bildladung je nach Browserfenster-Größe optimiert.','Website für eine Kosmetikmarke (Australien).','WordPress-Onlineshops inkl. Zahlungsintegration für mehrere Kunden.']),
   ]),
   ('Ausbildung',[
     ('2022 – 2025','Höhere Berufsausbildung in Webentwicklung','Spanien · HND in DAW · EQF Level 5 · Klassensprecher (3 Jahre)',[]),
     ('2011 – 2015','Diplom in Kommunikationsdesign','IN.D Institut für Design Düsseldorf · Note 1,4 · inkl. Webdesign',[]),
   ]),
   ('Hobbys & Nebenprojekte',[
     ('2023','Wettbewerbsprogrammierung','ProgramaMe (Team ElForLoop, Java)',['Regional: 2. Platz · National: 4. Platz · Finale Madrid (UCM): 10. Platz.']),
     ('','Codeforces & CodeAbbey','Handle „Messerschmitt“',['Dutzende gelöste Aufgaben in Rust; hunderte gelöste Probleme auf CodeAbbey.']),
   ]),
  ],
  style_k='Arbeitsweise', style='Kommunikationsstark in jeder Situation · dynamisch, denkt outside the box · Klassensprecher (3 Jahre)',
 ),
 'en': dict(
  name='Constantino Carneiro-Fernández',
  head='Fullstack Web Developer · Problem Solver · Cybersecurity Enthusiast',
  meta=[('Location','Regensburg, Germany',''),('Email','ccf.szilard@gmail.com','mailto:ccf.szilard@gmail.com'),('LinkedIn','constantino-c-2957731a2','https://www.linkedin.com/in/constantino-c-2957731a2'),('GitHub','Farkas404','https://github.com/Farkas404')],
  profile='I have been building software and websites since 2015. Development is my core business: PHP, Symfony, WordPress and TYPO3 are part of my daily routine. My degree in Communication Design (grade 1.4, top of the German scale) and higher vocational training in web development (DAW, Spain) also give me a trained eye for user guidance. At my core, I am a problem solver: I like taking things apart to understand how they really work (active on HackTheBox). Strongest programming language: Java.',
  skills_k='Skills',
  skills=[('Programming languages','Java, JavaScript, TypeScript, C++, Rust'),('CMS & fullstack','PHP, Symfony, WordPress, TYPO3'),('Frontend','Angular, TypeScript, Bootstrap 5.3'),('UX & problem-solving','Bridge between design and development, user guidance, iterative prototyping'),('Automation & AI','n8n, Ollama, Python/Streamlit'),('Languages','German (C1) · English & Spanish (native)')],
  sections=[
   ('Work experience',[
     ('Jun – Jul 2026','Freelance Fullstack Developer','Maheri Consulting Services Network · Security Monitoring Dashboard · project basis (6 weeks)',['Web dashboard for visualising security events (alerts, logs, system status), as a standalone tool and white-label component.','Frontend: Angular (TypeScript), responsive layout. Backend: PHP/Symfony, PostgreSQL data model.','Prepared integration of Wazuh/Suricata as a data source.','Git workflow (Sourcetree) with feature branches and deployment documentation.']),
     ('Nov 2025 – Jun 2026','Junior Fullstack Developer','TA Bildungszentrum · Website 4.0 project',['Independently built over 30 of the site’s 80+ CMS widgets (roughly one third): PHP 8.4, Symfony, Doctrine, Twig, SCSS, JavaScript.','Responsive layouts with Bootstrap 5.3; cleaned up legacy Tailwind components.','News module with CRUD, categories, filters and pagination.','Extended CKEditor workflows: media management, image picker, page picker, internal linking.','Git, feature branches, code review; biweekly sprints with YouTrack.']),
   ]),
   ('Selected projects',[
     ('','iOS photo-editing app','Co-developed in Swift and C++',['Native iOS app for photo editing, GPU-accelerated rendering via Metal.','Compute-intensive image processing in C++, connected to a Swift UI; open-source release planned.']),
     ('','IronGrid 2.0 – OT/IT Security Lab','Personal project',['Isolated network (Linux VMs, firewall, DNS, Apache), SCADA/HMI with OpenPLC/Modbus TCP.','Suricata (IDS), Wazuh (SIEM), monitoring with PostgreSQL/Grafana, automated via Ansible.']),
   ]),
   ('Additional experience',[
     ('Apr 2018','Co-speaker – Data Mining Seminar, Allianz SE','freelance',['Co-presented a two-day data mining workshop at Allianz SE headquarters, Munich.']),
     ('May 2016 – Apr 2018','Designer','Hesse Design GmbH, Düsseldorf / Shanghai',['Website & interface for “bola”: UX concept, widget development, tablet/mobile adaptation, Mailchimp integration.','UI/UX design, click-dummies and prototypes for several internal agency pages.','Wireframes & website concept for Juwelier Pletzsch (ring configurator).']),
     ('2015 – 2019','Freelance Developer','Düsseldorf',['Web widgets for the “SMS Website” (SMS Group, via LK Aktiengesellschaft), including Heavy Plate Mill, Hot Metal Treatment, SAF Ferro Alloys, SAF Silicon, Drive Technology.','Willy Heckmann (several months): product data maintenance for hundreds/thousands of products; optimised responsive image loading based on browser window size.','Website for a cosmetics brand (Australia).','WordPress online shops incl. payment integration for several clients.']),
   ]),
   ('Education',[
     ('2022 – 2025','Higher Vocational Training in Web Development','Spain · HND in Web Application Development (DAW) · EQF Level 5 · class representative (3 years)',[]),
     ('2011 – 2015','Degree in Communication Design','IN.D Institut für Design Düsseldorf · grade 1.4 · incl. web design',[]),
   ]),
   ('Hobbies & side projects',[
     ('2023','Competitive programming','ProgramaMe (team ElForLoop, Java)',['Regional: 2nd place · National: 4th place · National final, Madrid (UCM): 10th place.']),
     ('','Codeforces & CodeAbbey','handle “Messerschmitt”',['Dozens of problems solved in Rust; hundreds of problems solved on CodeAbbey.']),
   ]),
  ],
  style_k='Working style', style='Strong communicator in any situation · dynamic, thinks outside the box · class representative (3 years)',
 ),
}
